name: Build MAUI Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workloads
      run: dotnet workload install maui maui-android

    - name: Restore dependencies
      run: dotnet restore MyAccounts.Mobile/MyAccounts.Mobile.vbproj

    - name: Build MAUI Android
      run: dotnet publish MyAccounts.Mobile/MyAccounts.Mobile.vbproj -f net8.0-android -c Release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyAccounts-APK
        path: MyAccounts.Mobile/bin/Release/net8.0-android/publish/*.apk
